### ISSUE TITLE
Upgrade to cloudscribe 6, BS5 etc

### ISSUE THREAD

**Issue by CrispinF** [exeGesIS-SDM/exegesis-docs-website#10]
@JimKerslake  as discussed.
This will need new licensing files for TalkAbout Forums, and maybe something else??

**Comment by CrispinF** [comment]
Also please use new Exegesis logo "S:\Idox\Brand\ESDM_to_Idox_Branding\exegesis_idox_bg.jpg" 
If that's not the right size, there are other variants in same folder.

**Comment by CrispinF** [comment]
Also note this site has real client users viewing the documentation (though not many), so we should have the licensing files ready when deploying.

**Comment by JimKerslake** [comment]
Upgraded, published and merged to develop branch,

Residual brokenness of forum posts is expected (CS talkabout bug)

Note - This repo needs a bit of attention - 
it's not git-excluding a bunch of  .vs  type of files that perhaps it ought to be.
And likewise the node_modules want excluding.

**Comment by CrispinF** [comment]
@JimKerslake  the Submit button on this Contact Form doesn't look like a button.
https://docs.esdm.co.uk/librarylink/contact

I thought we'd resolved this one, but I see the button is class btn-default which I don't think exists in BS5, and should be btn-primary
Could you check this, and why it's still wrong in upgraded site? Has we overridden this view for some reason?

**Comment by JimKerslake** [comment]
@CrispinF   Yes there's about 30 view overrides lurking in there - I scanned them for any obvious major BS5 incompatibilities, but there's quite a lot of such minor fiddly BS4 >> 5 issues such as this, to try and snag...   
I can fix those up and maybe deploy again.

**Comment by CrispinF** [comment]
@JimKerslake I think this needs the upgraded Logger to resolve the XSS vulnerability.
CORRECTION - not needed, as this site doesn't use the ESDM Logger.
